services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_KEY=${API_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db                            # Container name for the database (see below)
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: arsenal_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

